### PR TITLE
InGas refactor

### LINKED ISSUE #75: InWater System needs some kind of damage icon on it
## Description

Currently you take damage without any indicator beyond inspecting yourself. Requires an icon (see barotrauma system).

Opening this to show it is known, i'll just use that H2O icon for now. May also refactor InWater a bit >:)

### PR DESCRIPTION
**Pull request by Lyroth001**
## About the PR

InWater now can be used to check for any (singular) gas, and should also be able to be called by systems, not needing the component (Havent tested that part tho). Closes #75 

## Technical details

read the code :godo:

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

InWater is now called InGas, parameters have been renamed accordingly

**Changelog**

### CODE REVIEW

**Comment by Lyroth001** [comment]
Closes #75, also see #76 should hopefully make it easier

**Comment by Lyroth001** [comment]
TECHNICALLY it says your drowning but like. Eh not sure where to change that so

**Comment by Pixeltheaertist** [comment]
Yeah I can fix the icon if you want, Jellids have a unique one so I can add it in my Jellid branch

**Comment by Lyroth001** [comment]
Its the text the icon displays on hover specifically

**Comment by Pixeltheaertist** [comment]
> Its the text the icon displays on hover specifically

Yeah Jellids use the same icon but their text is 

Plasmolysis

Your membrane is falling apart!

**Comment by Lyroth001** [comment]
> > Its the text the icon displays on hover specifically
> 
> Yeah Jellids use the same icon but their text is 
> 
> Plasmolysis
> 
> Your membrane is falling apart!

Oh neat, I'll check how you do that probablt tmrw then!

**Comment by Pixeltheaertist** [comment]
want me to merge this now or wait?

**Comment by Lyroth001** [comment]
Good to merge now, tested it and it works fine, actually clears the emote when not in the gas as well now lmao

**Comment by Pixeltheaertist** [comment]
copy copy, i can't test it but i trust you O7

**Comment by Pixeltheaertist** [comment]
@Lyroth001 do you know if it sets any kind of public variable to true or should i add that when i get home

like if an entity is in water it sets that fact to true so other systems can do special things if they are in water
i'm also going to make a new issue for things to have water to do that i need to code at some point

THANKS FOR THE CONTRIBUTION! 
This is big time help

**Comment by Lyroth001** [comment]
> @Lyroth001 do you know if it sets any kind of public variable to true or should i add that when i get home
> 
> like if an entity is in water it sets that fact to true so other systems can do special things if they are in water i'm also going to make a new issue for things to have water to do that i need to code at some point
> 
> THANKS FOR THE CONTRIBUTION! This is big time help

Currently no variable, but you should be able to call isinwater() to check, which should (In theory I havent tested it) be able to be called on entities without the component as well (although adding a var to the component wouldn't be too hard)

**Pull request merged**
